name: Python Pytest Github Action
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2.3.4
       - run : pip install -r requirements.txt && pytest
